[package]
name = "esexpr_text"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
esexpr = { path = "../esexpr" }
lalrpop-util = { version = "0.20.2", features = ["unicode", "lexer"] }
logos = "0.14.0"
hexfloat2 = "0.1.3"
num-bigint = "0.4.5"
